"""Add marketing_consent column to user

Revision ID: 1c8cbc0ff441
Revises: bb7e7cc01e09
Create Date: 2025-10-15 17:37:11.221444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8cbc0ff441'
down_revision = 'bb7e7cc01e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketing_consent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('marketing_consent')

    # ### end Alembic commands ###
