"""add_last_pricing_reminder_sent_at_to_user

Revision ID: 22aaab6d6596
Revises: 9310cd36f8dd
Create Date: 2025-11-02 20:33:57.152499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22aaab6d6596'
down_revision = '9310cd36f8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_pricing_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_pricing_reminder_sent_at')

    # ### end Alembic commands ###
