"""Add subscription plan fields to User model

Revision ID: 31bef69aec6b
Revises: b9caebc156d5
Create Date: 2025-10-13 17:38:36.034467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31bef69aec6b'
down_revision = 'b9caebc156d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_cycle', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('subscription_cycle')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
