"""add last_login_date column

Revision ID: 3e3172ee6730
Revises: add_device_fingerprint
Create Date: 2026-05-11 20:14:32.370450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e3172ee6730'
down_revision = 'add_device_fingerprint'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_ip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_blocked_ip_active'))
        batch_op.drop_index(batch_op.f('idx_blocked_ip_address'))
        batch_op.drop_index(batch_op.f('ix_blocked_ip_ip_address'))

    op.drop_table('blocked_ip')
    with op.batch_alter_table('letter', schema=None) as batch_op:
        batch_op.alter_column('is_send_to_myself',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_encrypted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # Clean up orphan media attachments before enforcing NOT NULL on letter_id
    op.execute('DELETE FROM media_attachment WHERE letter_id IS NULL;')
    with op.batch_alter_table('media_attachment', schema=None) as batch_op:
        batch_op.alter_column('letter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_media_expires'))
        batch_op.drop_index(batch_op.f('idx_media_temporary'))
        batch_op.drop_index(batch_op.f('idx_media_user_temporary'))
        batch_op.create_index('idx_media_user_letter', ['user_id', 'letter_id'], unique=False)
        batch_op.drop_column('expires_at')
        batch_op.drop_column('is_temporary')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_index(batch_op.f('idx_user_device_fingerprint'))
        batch_op.drop_column('device_fingerprint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_fingerprint', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_user_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.drop_column('last_login_date')

    with op.batch_alter_table('media_attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_temporary', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_media_user_letter')
        batch_op.create_index(batch_op.f('idx_media_user_temporary'), ['user_id', 'is_temporary'], unique=False)
        batch_op.create_index(batch_op.f('idx_media_temporary'), ['is_temporary'], unique=False)
        batch_op.create_index(batch_op.f('idx_media_expires'), ['expires_at'], unique=False)
        batch_op.alter_column('letter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('letter', schema=None) as batch_op:
        batch_op.alter_column('is_encrypted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_send_to_myself',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    op.create_table('blocked_ip',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blocked_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blocked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blocked_by'], ['user.id'], name=op.f('blocked_ip_blocked_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('blocked_ip_pkey'))
    )
    with op.batch_alter_table('blocked_ip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_ip_ip_address'), ['ip_address'], unique=True)
        batch_op.create_index(batch_op.f('idx_blocked_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('idx_blocked_ip_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###
