"""Add fingerprint_id to User

Revision ID: 510ed54e7c02
Revises: 3e3172ee6730
Create Date: 2026-05-22 15:12:07.900260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510ed54e7c02'
down_revision = '3e3172ee6730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fingerprint_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fingerprint_id')

    # ### end Alembic commands ###
