"""Add MediaAttachment model for letter media files

Revision ID: 52780c920460
Revises: 52a655910ea9
Create Date: 2025-08-30 16:25:42.838162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52780c920460'
down_revision = '52a655910ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter', schema=None) as batch_op:
        batch_op.drop_column('media_attachments')

    # ### end Alembic commands ###
