"""Add Notification model and confirmation_expires field

Revision ID: 52a655910ea9
Revises: f376003ce6fe
Create Date: 2025-08-30 16:02:46.207954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52a655910ea9'
down_revision = 'f376003ce6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trusted_contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_expires', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trusted_contact', schema=None) as batch_op:
        batch_op.drop_column('confirmation_expires')

    # ### end Alembic commands ###
