"""add_last_draft_reminder_sent_at_to_letter

Revision ID: 9310cd36f8dd
Revises: a017769c873b
Create Date: 2025-11-02 20:28:31.937460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9310cd36f8dd'
down_revision = 'a017769c873b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_draft_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter', schema=None) as batch_op:
        batch_op.drop_column('last_draft_reminder_sent_at')

    # ### end Alembic commands ###
