"""add_last_no_letter_reminder_sent_at_to_user

Revision ID: a017769c873b
Revises: 4c48aba4793d
Create Date: 2025-11-02 20:25:13.935476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a017769c873b'
down_revision = '4c48aba4793d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_no_letter_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_no_letter_reminder_sent_at')

    # ### end Alembic commands ###
