"""add_focus_keyword_to_blogpost

Revision ID: a56f6763aeaf
Revises: 1c8cbc0ff441
Create Date: 2025-10-18 11:58:35.364955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56f6763aeaf'
down_revision = '1c8cbc0ff441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus_keyword', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('focus_keyword')

    # ### end Alembic commands ###
