"""add death confirmation cooldown to trusted contact

Revision ID: add_cooldown_field
Revises: f376003ce6fe
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_cooldown_field'
down_revision = 'f376003ce6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_contact', sa.Column('death_confirmation_cooldown_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trusted_contact', 'death_confirmation_cooldown_until')
    # ### end Alembic commands ###

