"""add_blocked_ip_model

Revision ID: b192bfb864ff
Revises: 22aaab6d6596
Create Date: 2025-11-05 19:28:34.613851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b192bfb864ff'
down_revision = '22aaab6d6596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('blocked_by', sa.Integer(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_index('idx_blocked_ip_address', 'blocked_ip', ['ip_address'], unique=False)
    op.create_index('idx_blocked_ip_active', 'blocked_ip', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_blocked_ip_active', table_name='blocked_ip')
    op.drop_index('idx_blocked_ip_address', table_name='blocked_ip')
    op.drop_table('blocked_ip')
    # ### end Alembic commands ###
