"""Add enhanced subscription tracking fields

Revision ID: bb7e7cc01e09
Revises: 31bef69aec6b
Create Date: 2025-10-13 17:54:10.764957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7e7cc01e09'
down_revision = '31bef69aec6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('subscription_cancel_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('subscription_cancel_at_period_end', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_payment_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('next_payment_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('subscription_trial_end', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_trial_end')
        batch_op.drop_column('next_payment_date')
        batch_op.drop_column('last_payment_date')
        batch_op.drop_column('subscription_cancel_at_period_end')
        batch_op.drop_column('subscription_cancel_at')
        batch_op.drop_column('subscription_end_date')

    # ### end Alembic commands ###
