"""add_ip_tracking_to_user

Revision ID: c8b2888c53fb
Revises: b192bfb864ff
Create Date: 2025-11-05 19:29:58.155879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b2888c53fb'
down_revision = 'b192bfb864ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns already exist
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('user')]
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        if 'last_login_ip' not in columns:
            batch_op.add_column(sa.Column('last_login_ip', sa.String(length=45), nullable=True))
        if 'registration_ip' not in columns:
            batch_op.add_column(sa.Column('registration_ip', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_ip')
        batch_op.drop_column('last_login_ip')

    # ### end Alembic commands ###
