"""add plan column to user

Revision ID: cf9d2ffe2ad3
Revises: bb7e7cc01e09
Create Date: 2025-10-13 19:04:40.450799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9d2ffe2ad3'
down_revision = 'bb7e7cc01e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_cycle', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('subscription_cancel_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('subscription_cancel_at_period_end', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_payment_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('next_payment_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('subscription_trial_end', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_trial_end')
        batch_op.drop_column('next_payment_date')
        batch_op.drop_column('last_payment_date')
        batch_op.drop_column('subscription_cancel_at_period_end')
        batch_op.drop_column('subscription_cancel_at')
        batch_op.drop_column('subscription_end_date')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('subscription_cycle')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
