"""Add delay_after_verification to Letter model

Revision ID: f10a4503a665
Revises: 
Create Date: 2025-08-24 12:30:26.431847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10a4503a665'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delay_after_verification', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter', schema=None) as batch_op:
        batch_op.drop_column('delay_after_verification')

    # ### end Alembic commands ###
