"""Add 2FA and password reset fields to User model

Revision ID: f376003ce6fe
Revises: b0a6156f91bb
Create Date: 2025-08-24 12:58:38.251909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f376003ce6fe'
down_revision = 'b0a6156f91bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_unique_constraint(None, ['password_reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('backup_codes')
        batch_op.drop_column('two_factor_secret')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('password_reset_expires')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
